from . import rib

TITLE = "RELEVÉ D’IDENTITÉ BANCAIRE / IBAN"

CIVILITE = "M."
NOM = "MARTIN"
PRENOM = "LUCAS"
TITULAIRE_NOM = "M. MARTIN LUCAS"
ADRESSE = "12 RUE DES FLEURS"
TITULAIRE_RUE = "12 RUE DES FLEURS"
CP = "75011"
VILLE = "PARIS"
TITULAIRE_VILLE = "75011 PARIS"

AGENCE = "AGENCE TOULOUSE CAPITOLE"
AGENCE_RUE = "1 PLACE DU CAPITOLE"
AGENCE_CP = "31000"
AGENCE_VILLE = "TOULOUSE"

BANQUE = "30003"
GUICHET = "00001"
COMPTE = "00012345678"
CLE = rib.cle_rib(BANQUE, GUICHET, COMPTE)
IBAN = rib.iban_fr(BANQUE, GUICHET, COMPTE, CLE)
BIC = "SOGEFRPPXXX"

LABEL_TITULAIRE = "Titulaire"
LABEL_AGENCE = "Agence de domiciliation"
LABEL_RIB = "RIB"
LABEL_IBAN = "IBAN"
LABEL_BIC = "BIC"
COL_BANQUE = "Banque"
COL_GUICHET = "Guichet"
COL_COMPTE = "Compte"
COL_CLE = "Clé RIB"
