# ----------------------------------------------------------------------

SERVICE_LABEL = "Service clients"
SERVICE_ASSISTANCE = "Assistance : FAQ sur le site "
SERVICE_URL = "www.sfr-discover.fr"
SERVICE_DOT = "."
SERVICE_PHONE = "Numéro du service client : 09 70 83 10 23 ou 1023 depuis une ligne"
SERVICE_SFR = "SFR "
SERVICE_SIEGE = "Siège social : 16 rue du Général Alain de Boissieu 75015 Paris "

COMPANY_BRAND = "SFR Discover"
COMPANY_INFO = "information"
COMPANY_SERVICE = "SFR Discover - Service Client"
COMPANY_ADDRESS = "16 rue du Général Alain de Boissieu 75015 Paris"
COMPANY_CAPITAL = "SA au capital de 3 423 265 720 Euro - RCS de Paris 343 059 564"
COMPANY_TVA = "N° de TVA intracommunautaire: FR 71 343 059 564 - APE : 6120Z"

NOM = "Martin"
PRENOM = "Lucas"
CLIENT_NOM = "LUCAS MARTIN"

ACCOUNT_TITULAIRE_LABEL = "Titulaire ligne"
ACCOUNT_TITULAIRE_NAME = "LUCAS MARTIN"
ACCOUNT_COMPTE_LABEL = "N° de compte client"
ACCOUNT_COMPTE_NUM = "2LH5L"
ACCOUNT_FACTURE_LABEL = "Date et N° Facture"
ACCOUNT_FACTURE_VAL = "2026-09-01 - 169793"

RECIPIENT_NOM = "LUCAS MARTIN"
RECIPIENT_ADRESSE = "12 Rue des Fleurs"
RECIPIENT_CP_VILLE = "75011 Paris"

RECAP_L1_LABEL = "Montant HT soumis à TVA :"
RECAP_L1_VAL = "6.25€"
RECAP_L2_LABEL = "Montant total TVA (20.0 %) :"
RECAP_L2_VAL = "1.25€"
RECAP_L3_LABEL = "MONTANT TOTAL FACTURE TTC"
RECAP_L3_VAL = "7.5€"
RECAP_L4_LABEL = "Solde HT en votre faveur avant la facturation :"
RECAP_L4_VAL = "0€"
RECAP_L5_LABEL = "Solde TTC en votre faveur avant la facturation :"
RECAP_L5_VAL = "0€"
RECAP_L6_LABEL = "Montant total à payer HT"
RECAP_L6_VAL = "6.25€"
RECAP_L7_LABEL = "Montant total à payer TTC"
RECAP_L7_VAL = "7.5€"

BANNER_TITLE = "FACTURE SFR DISCOVER"

COL_NUM_LIGNE = "NUMÉRO DE LIGNE"
COL_DESCRIPTION = "DESCRIPTION"
COL_DATE = "DATE"
COL_MONTANT_L1 = "Montant"
COL_MONTANT_L2 = "€ TTC"

ITEM_NUM_LIGNE = ""
ITEM_DESCRIPTION = "Penalites de retard pour echec de prelevement: 7.5 €"
ITEM_DATE = "2026-09-01"
ITEM_MONTANT_TTC = "7.5€"

TOTAL_HT_LABEL = "TOTAL FACTURE HT"
TOTAL_HT_VAL = "6.25"
TOTAL_TTC_LABEL = "TOTAL FACTURE TTC"
TOTAL_TTC_VAL = "7.5"
TVA_ENCAISSEMENT = "TVA sur les Encaissements"

FOOTER_NOTE = "* Les montants unitaires sont arrondis, leur somme peut différer du montant total."
FOOTER_SEPA_L1 = "Le prélèvement de votre facture se fera sur le compte no FPELFR21 FR76XXXXXXXXXXXXXXX5545 par l'ICS n° xxx"
FOOTER_SEPA_L2 = "conformément à votre Mandat de prélèvement SEPA référencé 2LH5L-00000 le 2026-10-01."
