LIMITS = {
    "max_rows": 3,
    "duplicata": 30,
    "contact_line_0": 45,
    "contact_line_1": 45,
    "contact_line_2": 30,
    "contact_line_3": 30,
    "contact_line_4": 30,
    "client_nom": 40,
    "client_email": 45,
    "client_tel": 25,
    "vente_title": 20,
    "oper": 25,
    "trans": 25,
    "store": 20,
    "store_num": 10,
    "date_str": 35,
    "page_info": 20,
    "vendeur": 25,
    "ref": 20,
    "desc": 50,
    "qty": 10,
    "unit_price": 15,
    "total": 15,
    "article_ref": 20,
    "article_desc": 50,
    "article_qty": 10,
    "article_unit_price": 15,
    "article_total": 15,
    "count_label": 25,
    "total_facture": 15,
    "payment_method": 20,
    "payment_amount": 15,
    "rendu_amount": 15,
    "total_ht": 15,
    "tva_product": 25,
    "tva_rate": 15,
    "tva_amount": 15,
    "total_ttc": 15,
    "code": 20,
    "line_0": 130,
    "line_1": 110,
    "line_2": 120,
    "line_3": 50,
    "line_4": 80,
}

# ----------------------------------------------------------------------

def public_limits() -> dict:
    return dict(LIMITS)

